version: '2'
services:
    mysql:
        volumes:
            - var-lib-mysql:/var/lib/mysql
    phpfpm:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/phpfpm
        volumes:
            - storage-app:/usr/share/nginx/WEBAPP/storage/app
volumes:
    storage-app:
        driver: local
    var-lib-mysql:
        driver: local
