version: '2'
services:
    mysql:
        image: mysql:5.6.28
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
    phpfpm:
        expose:
            - "9000"
    nginxhttps:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/nginxhttps
        volumes_from:
            - nginxhttp:ro
            - phpfpm:ro
        ports:
            - "443:443"
    nginxhttp:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/nginxhttp
        ports:
            - "80:80"
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
volumes:
    etc-letsencrypt:
        driver: local
networks:
    default:
        driver: bridge
