version: '2'
services:
    webapp.dev:
        image: rasodu/s3mock:0.2.1
        command: -r /fakes3_root -p 4569 --hostname webapp.dev
        ports:
            - "4569:4569"
    phpfpm:
        image: rasodu/phpfpmdev:5.6.1
        volumes:
            - .:/usr/share/nginx/WEBAPP
    cmd:
        image: rasodu/cmd:5.6.1
        volumes_from:
            - phpfpm
