version: '2'
services:
    mysql:
        image: mysql:${DLEMPFAST_RASODU_MYSQL_VERSION}
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=homestead
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
