version: '2'
services:
    httpbackend:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_RASODU_HTTPBACKENDLARAVELNGINX_DOCKERFILE_DIR}com/rasodu/httpbackendlaravelnginx/httpbackendlaravelnginx
            args:
                DLEMPFAST_PROJECT_DIR: ${DLEMPFAST_PROJECT_DIR}
        expose:
            - "80"
