version: '2'
services:
    phpfpm:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_RASODU_PHPFPMLARAVEL_DOCKERFILE_DIR}com/rasodu/phpfpmlaravel/${DLEMPFAST_RASODU_PHPFPMLARAVEL_VERSION}phpfpmlaravel
            args:
                DLEMPFAST_RASODU_PHPFPMLARAVEL_CONFIG_DIR: ${DLEMPFAST_RASODU_PHPFPMLARAVEL_CONFIG_DIR}
                DLEMPFAST_PROJECT_DIR: ${DLEMPFAST_PROJECT_DIR}
        expose:
            - "9000"
