version: '2'
services:
    http:
        image: rasodu/httpnginx:1.10.2
        ports:
            - "80:80"
        volumes:
            - acme-challenge:/DLEMP/letsencrypt/public/.well-known/acme-challenge
    https:
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
    certbot:
        image: rasodu/certbot:0.9.3
        depends_on:
            - https
        volumes_from:
            - http:rw
        volumes:
            - etc-letsencrypt:/etc/letsencrypt
            - var-lib-letsencrypt:/var/lib/letsencrypt
volumes:
    acme-challenge:
        driver: local
    var-lib-letsencrypt:
        driver: local
