version: '2'
services:
    https:
        image: rasodu/httpsnginx:1.10.1
        depends_on:
            - httpbackend
        ports:
            - "443:443"
volumes:
    etc-letsencrypt:
        driver: local
