version: '2'
services:
    phpfpm:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/56phpfpmdevlaravel
        volumes:
            - ${DLEMPFAST_CONTEXT}${DLEMPFAST_PROJECT_DIR}:/usr/share/nginx/WEBAPP
    cmd:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/56cmdlaravel
            args:
                DLEMPFAST_CONFIG_DIR: ${DLEMPFAST_CONFIG_DIR}
        ports:
            - "3002:3000"
            - "3001:3001"
        volumes_from:
            - phpfpm
