version: '2'
services:
    phpfpm:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/56phpfpm
        expose:
            - "9000"
