version: '2'
services:
    phpfpm:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}docker/dockerfile/phpfpmdev56
        volumes:
            - ${DLEMPFAST_CONTEXT}:/usr/share/nginx/WEBAPP
    cmd:
        image: rasodu/cmd:5.6.1
        volumes_from:
            - phpfpm
