version: '2'
services:
    phpfpm:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}services/dockerfile/${DLEMPFAST_RASODU_PHPFPMLARAVEL_VERSION}phpfpmdevlaravel
        volumes:
            - ${DLEMPFAST_CONTEXT}${DLEMPFAST_PROJECT_DIR}:/usr/share/nginx/WEBAPP
    cmd:
        build:
            context: ${DLEMPFAST_CONTEXT}
            dockerfile: ${DLEMPFAST_BASE_DIR}services/dockerfile/${DLEMPFAST_RASODU_PHPFPMLARAVEL_VERSION}cmdlaravel
            args:
                DLEMPFAST_CONFIG_DIR: ${DLEMPFAST_CONFIG_DIR}
        ports:
            - "3001:3001"
            - "3002:3002"
        volumes_from:
            - phpfpm
